-- Run this once in Supabase SQL Editor before using the HR portal.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'candidate' check (role in ('candidate', 'hr', 'admin')),
  created_at timestamptz not null default now()
);

alter table public.cv_history add column if not exists status text not null default 'new'
  check (status in ('new', 'reviewing', 'interview', 'passed', 'rejected'));

create table if not exists public.candidate_notes (
  id bigint generated by default as identity primary key,
  cv_id text not null,
  candidate_id uuid references auth.users(id) on delete cascade,
  body text not null check (char_length(body) <= 2000),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create or replace function public.current_user_is_hr()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role in ('hr', 'admin'));
$$;

drop policy if exists "profiles: own or HR" on public.profiles;
create policy "profiles: own or HR" on public.profiles for select using (id = auth.uid() or public.current_user_is_hr());
drop policy if exists "cv history: HR can read" on public.cv_history;
create policy "cv history: HR can read" on public.cv_history for select using (public.current_user_is_hr());
drop policy if exists "cv history: HR can update status" on public.cv_history;
create policy "cv history: HR can update status" on public.cv_history for update using (public.current_user_is_hr()) with check (public.current_user_is_hr());
drop policy if exists "candidate notes: HR manages" on public.candidate_notes;
create policy "candidate notes: HR manages" on public.candidate_notes for all using (public.current_user_is_hr()) with check (public.current_user_is_hr());

-- Create a profile automatically for every new account.
create or replace function public.create_profile_for_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email) values (new.id, new.email) on conflict (id) do nothing;
  return new;
end;
$$;
drop trigger if exists create_profile_after_signup on auth.users;
create trigger create_profile_after_signup after insert on auth.users for each row execute procedure public.create_profile_for_new_user();

-- Promote a trusted account manually; never expose this action to candidate users.
-- update public.profiles set role = 'hr' where email = 'hr@your-company.com';
