-- ============================================================================
-- SQL Setup: ระบบการแจ้งเตือน (Notifications System)
-- ============================================================================
-- รันโค้ดชุดนี้ใน Supabase Dashboard -> SQL Editor
-- ============================================================================

-- 1. สร้างตาราง notifications
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,                         -- หัวข้อการแจ้งเตือน เช่น "อัปเดตสถานะการสมัครงาน"
  message TEXT NOT NULL,                       -- ข้อความแจ้งเตือนรายละเอียด
  type TEXT DEFAULT 'status_update',           -- ประเภท เช่น status_update, interview, system
  related_cv_id TEXT,                          -- ID ของ CV ที่เกี่ยวข้อง (เป็น UUID / TEXT ให้ตรงกับ cv_history.id)
  is_read BOOLEAN NOT NULL DEFAULT FALSE,      -- อ่านแล้วหรือยัง (false = แสดงจุดแดงที่กระดิ่ง)
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. ปรับประเภทของ column related_cv_id ให้เป็น TEXT (กรณีที่เคยสร้างตารางเป็น BIGINT ไว้ก่อนหน้านี้)
ALTER TABLE public.notifications ALTER COLUMN related_cv_id TYPE text;

-- 3. เปิดใช้งาน Row-Level Security (RLS)
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- 4. ลบ Policy เดิมหากเคยมีอยู่ เพื่อป้องกันชื่อซ้ำ
DROP POLICY IF EXISTS "Users can view own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can mark own notifications as read" ON public.notifications;
DROP POLICY IF EXISTS "Allow insert notifications" ON public.notifications;

-- 5. กำหนด Policy: ผู้ใช้ดูได้เฉพาะการแจ้งเตือนของตัวเอง
CREATE POLICY "Users can view own notifications"
ON public.notifications FOR SELECT
USING (auth.uid() = user_id);

-- 6. กำหนด Policy: ผู้ใช้อัปเดตสถานะ (เช่น กดอ่านแล้ว is_read = true) เฉพาะของตัวเอง
CREATE POLICY "Users can mark own notifications as read"
ON public.notifications FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 7. กำหนด Policy: อนุญาตให้ระบบ / Backend สามารถส่งการแจ้งเตือนเข้ามาได้
CREATE POLICY "Allow insert notifications"
ON public.notifications FOR INSERT
TO public
WITH CHECK (true);

-- 8. เปิดสิทธิ์ Realtime สำหรับตาราง notifications (เพื่อให้กระดิ่งเด้งสดทันที)
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
